-- This module defines the shaders needed to render the base of the house
module CardShader where

cardVertexShaderSource :: String
cardVertexShaderSource = unlines [
    "#version 330 core"
    ,"layout (location = 0) in vec3 position;"
    ,"layout (location = 1) in vec2 texCoord;"
    ,"layout (location = 2) in vec3 normal;"

    ,"out vec2 TexCoord;"
    ,"out vec3 Normal;"
    ,"out vec3 FragPos;"
    ,"uniform mat4 model;"
    ,"uniform mat4 view;"
    ,"uniform mat4 projection;"

    ,"void main()"
    ,"{"
    ,"    gl_Position = projection * view * model * vec4(position, 1.0f);"
    ,"    TexCoord = vec2(texCoord.x, 1.0 - texCoord.y);"
    ,"    FragPos = vec3(model * vec4(position,1.0f));"
    ,"    Normal = mat3(transpose(inverse(model))) * normal;"
    ,"}"]

cardFragmentShaderSource :: String
cardFragmentShaderSource = unlines [
    "#version 330 core"
    ,"in vec2 TexCoord;"
    ,"in vec3 Normal;"
    ,"in vec3 FragPos;"
    ,"out vec4 color;"

    ,"uniform vec3 lightPos;"
    ,"uniform vec3 viewPos;"
    ,"uniform vec3 objectColor;"
    ,"uniform vec3 lightColor;"
    ,"// 2D Random"
    ,"float random (in vec2 st) {"
    ,   "return fract(sin(dot(st.xy,vec2(12.280,424.470)))* 14342.934);"
    ,"}"
    ,"float noise (in vec2 st) {"
    ,"vec2 i = floor(st);"
    ,"vec2 f = fract(st);"
    ,"// Four corners in 2D of a tile"
    ,"float a = random(i);"
    ,"float b = random(i + vec2(1.0, 0.0));"
    ,"float c = random(i + vec2(0.0, 1.0));"
    ,"float d = random(i + vec2(1.0, 1.0));"
    ,"// Cubic Hermine Curve."
    ,"vec2 u = smoothstep(-0.076,1.,f);"
    ,"    //Mix 4 coorners percentages"
    ,"    return mix(a, b, u.x) + (c - a)* u.y * (1.0 - u.x) + (d - b) * u.x * u.y;"
    ,"}"
    ,"uniform sampler2D cardTexture;"
    ,"void main()"
    ,"{"
    ,"    float ambientStrength = 0.1f;"
    ,"    vec3 ambient = lightColor * ambientStrength;"
    ,"    // diffuse"
    ,"    vec3 lightDir = normalize(lightPos - FragPos);"
    ,"    float diff = max(dot(Normal, lightDir),0.0);"
    ,"    vec2 pos = vec2(TexCoord*50);"
    ,"    float n = noise(pos);"
    ,"    vec3 specColor= objectColor + lightColor * lightDir * diff;"
    ,"    vec3 diffuse = diff * lightColor;"
    ,"    // specular"
    ,"    float specularStrength = 3.0f;"
    ,"    vec3 viewDir = normalize(viewPos - FragPos);"
    ,"    vec3 reflectDir = reflect(-lightDir, Normal);"
    ,"    float spec = pow(max(dot(viewDir, reflectDir),0.0),25);"
    ,"    vec3 specular = specularStrength * spec * specColor;"  
    ,"    vec3 result = (ambient + diffuse + specular);"
    ,"    color = vec4(result, 1.0f) * texture(cardTexture, TexCoord) + vec4((0.1f * specColor),1.0f);"
    ,"}"]